export const dashboardData = {
  anomalyToday: {
    today: 3,
    yesterdayPercent: 25,
  },
  anomalyInAWeek: {
    week: 10,
    lastWeekPercent: 20,
  },
  lastDetected: {
    potId: "POT-N",
    time: "12.45",
  },
  potList: [
    { id: "POT-A", temp: 29, humidity: 68, soilMoisture: 55, battery: 87, status: "online"  },
    { id: "POT-B", temp: 33, humidity: 72, soilMoisture: 40, battery: 45, status: "offline" },
    { id: "POT-C", temp: 27, humidity: 58, soilMoisture: 62, battery: 91, status: "online"  },
    { id: "POT-D", temp: 35, humidity: 80, soilMoisture: 30, battery: 22, status: "online"  },
    { id: "POT-E", temp: 26, humidity: 65, soilMoisture: 75, battery: 78, status: "online"  },
    { id: "POT-F", temp: 31, humidity: 77, soilMoisture: 48, battery: 55, status: "offline" },
    { id: "POT-G", temp: 28, humidity: 61, soilMoisture: 53, battery: 63, status: "online"  },
    { id: "POT-H", temp: 30, humidity: 70, soilMoisture: 35, battery: 14, status: "online"  },
    { id: "POT-I", temp: 24, humidity: 55, soilMoisture: 80, battery: 99, status: "online"  },
    { id: "POT-J", temp: 36, humidity: 83, soilMoisture: 22, battery: 37, status: "offline" },
    { id: "POT-K", temp: 27, humidity: 64, soilMoisture: 70, battery: 82, status: "online"  },
    { id: "POT-L", temp: 32, humidity: 74, soilMoisture: 44, battery: 60, status: "online"  },
    { id: "POT-M", temp: 29, humidity: 69, soilMoisture: 58, battery: 48, status: "online"  },
    { id: "POT-N", temp: 34, humidity: 78, soilMoisture: 28, battery: 19, status: "offline" },
    { id: "POT-O", temp: 25, humidity: 57, soilMoisture: 77, battery: 95, status: "online"  },
    { id: "POT-P", temp: 31, humidity: 71, soilMoisture: 42, battery: 73, status: "online"  },
    { id: "POT-Q", temp: 28, humidity: 63, soilMoisture: 66, battery: 51, status: "online"  },
    { id: "POT-R", temp: 33, humidity: 76, soilMoisture: 33, battery: 30, status: "offline" },
    { id: "POT-S", temp: 26, humidity: 60, soilMoisture: 72, battery: 88, status: "online"  },
    { id: "POT-T", temp: 30, humidity: 67, soilMoisture: 50, battery: 42, status: "online"  },
    { id: "POT-U", temp: 35, humidity: 82, soilMoisture: 25, battery: 11, status: "offline" },
    { id: "POT-V", temp: 27, humidity: 62, soilMoisture: 68, battery: 76, status: "online"  },
    { id: "POT-W", temp: 29, humidity: 66, soilMoisture: 57, battery: 67, status: "online"  },
    { id: "POT-X", temp: 32, humidity: 75, soilMoisture: 38, battery: 84, status: "online"  },
    { id: "POT-Y", temp: 28, humidity: 59, soilMoisture: 73, battery: 93, status: "online"  },
    { id: "POT-Z", temp: 34, humidity: 79, soilMoisture: 20, battery: 26, status: "offline" },
  ],
};